### ISSUE TITLE
Support liquid 4

### ISSUE THREAD

**Issue by swsnr** [bdesham/reading_time#3]
I'd like to use this plugin in my blog.  However, my blog runs on Jekyll 3.5 which in turn uses Liquid 4 which does plugin doesn't support per its gemspec.  Could you update it to Liquid 4?

I'm not familiar with Ruby, Jekyll, Liquid or anything involved so I'm afraid I can't help much :(

**Comment by bdesham** [comment]
This has been fixed in version 1.1.3, which has been pushed to RubyGems.
